name: CBOM Vulnerability Analysis

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CODEQL_VERSION: v2.21.2
  CODEQL_DIR: ${{ github.workspace }}/codeql
  CBOM_TOOL_DIR: ${{ github.workspace }}/.cbom-tool
  CUSTOM_BUILD_COMMAND: ""  # e.g., "make", "npm run build"

jobs:
  cbom-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository to Analyze
      uses: actions/checkout@v4
      with:
        path: repo-to-scan

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Essential Build Tools
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends \
          python3-dev python3-venv git curl

    - name: Install build dependencies
      run: |
        # Update repository information
        
        # Install essential build tools
        sudo apt-get install -y build-essential autoconf automake libtool pkg-config cmake clang gcc g++ make
        
        # Install curl-specific dependencies including libpsl
        sudo apt-get install -y libssl-dev zlib1g-dev libnghttp2-dev
        sudo apt-get install -y libpsl-dev  # Add libpsl development package
        sudo apt-get install -y libidn2-dev  # For IDN support
        sudo apt-get install -y libssh2-1-dev  # For SSH support
        sudo apt-get install -y libkrb5-dev  # For Kerberos support
        sudo apt-get install -y librtmp-dev  # For RTMP support
        sudo apt-get install -y libldap2-dev  # For LDAP support
        sudo apt-get install -y libgnutls28-dev  # Alternative TLS library
        sudo apt-get install -y libcurl4-openssl-dev  # For development headers
        
        # Verify installation of critical packages
        echo "Verifying installed packages:"
        dpkg -l | grep -E 'libssl-dev|libpsl-dev|zlib1g-dev|libnghttp2-dev'
        
        # Print pkgconfig information for libpsl to verify it's correctly detected
        echo "PKG-CONFIG information for libpsl:"
        pkg-config --modversion libpsl || echo "libpsl not found in pkgconfig"
        pkg-config --libs libpsl || echo "No libs for libpsl found"
        pkg-config --cflags libpsl || echo "No cflags for libpsl found"
        
        # List the target directory contents for debugging
        echo "Target directory contents:"
        ls -la ${{ github.workspace }}
        if [ -d "curl" ]; then
          echo "Curl directory contents:" 
          ls -la curl/
        fi

    - name: Cache CodeQL CLI
      id: codeql-cache
      uses: actions/cache@v4
      with:
        path: ${{ env.CODEQL_DIR }}
        key: codeql-${{ env.CODEQL_VERSION }}
        restore-keys: |
          codeql-

    - name: Setup CodeQL CLI
      run: |
        # Download and extract CodeQL CLI
        mkdir -p $HOME/codeql-cli
        wget -q https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.21.3/codeql-bundle-linux64.tar.gz -O codeql-bundle.tar.gz
        tar -xzf codeql-bundle.tar.gz -C $HOME/codeql-cli
        
        # Find the codeql executable and set paths
        CODEQL_PATH=$(find $HOME/codeql-cli -name codeql -type f | head -n 1)
        CODEQL_DIR=$(dirname "$CODEQL_PATH")
        
        # Set the paths in GITHUB_ENV to persist across steps
        echo "CODEQL_PATH=${CODEQL_PATH}" >> $GITHUB_ENV
        echo "CODEQL_DIR=${CODEQL_DIR}" >> $GITHUB_ENV
        echo "${CODEQL_DIR}" >> $GITHUB_PATH
        
        # Debug: Show CodeQL directory structure
        echo "CodeQL directory contents:"
        find $HOME/codeql-cli -type f -name "codeql*" | sort
        
        # Verify installation
        "${CODEQL_PATH}" --version

    - name: Clone CBOM Analysis Tool
      uses: actions/checkout@v4
      with:
        repository: Namokar100/tool  # Fixed repository format
        path: ${{ env.CBOM_TOOL_DIR }}
        token: ${{ secrets.PAT_TOKEN }}

    - name: Install CBOM Tool Dependencies
      run: |
        cd ${{ env.CBOM_TOOL_DIR }}
        python -m pip install --upgrade pip setuptools wheel
        python -m venv venv
        source venv/bin/activate
        # Install dependencies first
        pip install -r requirements.txt
        # Install the package in development mode
        pip install -e .
        # Create a wrapper script
        echo '#!/bin/bash
        source ${{ env.CBOM_TOOL_DIR }}/venv/bin/activate
        export PYTHONPATH="${PYTHONPATH}:${{ env.CBOM_TOOL_DIR }}"
        python -m calyptra_ql.cli "$@"' > run-analysis.sh
        chmod +x run-analysis.sh
        # Verify installation
        ./venv/bin/python -c "import calyptra_ql; print('Package found at:', calyptra_ql.__file__)"

    - name: Run CBOM Analysis
      id: cbom-analysis
      run: |
        cd ${{ env.CBOM_TOOL_DIR }}
        mkdir -p ../analysis-results
        
        # Run the analysis using the wrapper script
        ./run-analysis.sh "${{ github.workspace }}" \
          --codeql-path "${{ env.CODEQL_PATH }}" \
          --codeql-threads 4 \
          --output-cbom ../analysis-results/cbom.json \
          --output-compliance ../analysis-results/compliance_report.txt \
          -v
  
        if [ ! -f ../analysis-results/cbom.json ] || [ ! -f ../analysis-results/compliance_report.txt ]; then
          echo "::error::CBOM analysis failed to produce output files"
          exit 1
        fi 

    - name: Check for Vulnerabilities
      id: check-vulnerabilities
      run: |
        if grep -q "violations found" analysis-results/compliance_report.txt; then
          echo "has_vulnerabilities=true" >> $GITHUB_ENV
          echo "::warning::Security vulnerabilities were found in the analysis"
        else
          echo "has_vulnerabilities=false" >> $GITHUB_ENV
          echo "No security vulnerabilities found"
        fi

    - name: Upload Analysis Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cbom-analysis-results
        path: |
          analysis-results/cbom.json
          analysis-results/compliance_report.txt
        retention-days: 7

    - name: Create Analysis Summary
      if: always()
      run: |
        echo "## CBOM Analysis Results" >> $GITHUB_STEP_SUMMARY
        echo "Analysis completed at: $(date)" >> $GITHUB_STEP_SUMMARY
        echo "### Compliance Report" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        cat analysis-results/compliance_report.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

    - name: Fail if Vulnerabilities Found
      if: env.has_vulnerabilities == 'true'
      run: |
        echo "Security vulnerabilities were found in the analysis"
        exit 1
