name: BCAE action

on: [push]

jobs:
  cbom-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run CBOM Analysis
        uses: Namokar100/cbae-action@v1.0.6
        with:
          token: ${{ secrets.PAT_TOKEN }}
