name: CBOM Vulnerability Analysis with CLI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CODEQL_VERSION: v2.21.2
  CODEQL_DIR: ${{ github.workspace }}/codeql
  CBOM_TOOL_DIR: ${{ github.workspace }}/.cbom-tool
  ANALYSIS_OUTPUT_DIR: ${{ github.workspace }}/analysis-results

jobs:
  cbom-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Current Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Essential Build Tools
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends \
          python3-dev python3-venv git curl build-essential

    - name: Install build dependencies
      run: |
        sudo apt-get install -y build-essential autoconf automake libtool pkg-config cmake clang gcc g++ make
        sudo apt-get install -y libssl-dev zlib1g-dev libnghttp2-dev
        sudo apt-get install -y libpsl-dev libidn2-dev libssh2-1-dev
        sudo apt-get install -y libkrb5-dev librtmp-dev libldap2-dev
        sudo apt-get install -y libgnutls28-dev libcurl4-openssl-dev

    - name: Setup CodeQL CLI
      run: |
        mkdir -p $HOME/codeql-cli
        wget -q https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.21.3/codeql-bundle-linux64.tar.gz -O codeql-bundle.tar.gz
        tar -xzf codeql-bundle.tar.gz -C $HOME/codeql-cli
        CODEQL_PATH=$(find $HOME/codeql-cli -name codeql -type f | head -n 1)
        CODEQL_DIR=$(dirname "$CODEQL_PATH")
        echo "CODEQL_PATH=${CODEQL_PATH}" >> $GITHUB_ENV
        echo "CODEQL_DIR=${CODEQL_DIR}" >> $GITHUB_ENV
        echo "${CODEQL_DIR}" >> $GITHUB_PATH
        "${CODEQL_PATH}" --version

    - name: Clone CBOM Analysis Tool
      uses: actions/checkout@v4
      with:
        repository: Namokar100/tool
        path: ${{ env.CBOM_TOOL_DIR }}
        token: ${{ secrets.PAT_TOKEN }}

    - name: Install CBOM Tool Dependencies
      run: |
        cd ${{ env.CBOM_TOOL_DIR }}
        python -m pip install --upgrade pip setuptools wheel
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install -e .

    - name: Create Analysis Directory
      run: |
        mkdir -p ${{ env.ANALYSIS_OUTPUT_DIR }}

    - name: Run CBOM Analysis
      run: |
        cd ${{ env.CBOM_TOOL_DIR }}
        source venv/bin/activate
        
        # Get absolute path of repository to analyze
        REPO_PATH="${{ github.workspace }}"
        
        # Use the FastAPI rules file for consistency
        RULES_PATH="${{ env.CBOM_TOOL_DIR }}/data/default_rules.yaml"
        
        # Run the CLI analysis
        python calyptra_ql/cli.py \
          "${REPO_PATH}" \
          --build-command "autoreconf -fi && ./configure --with-openssl && make -j$(nproc)" \
          -o "${{ env.ANALYSIS_OUTPUT_DIR }}/cbom.json" \
          -c "${{ env.ANALYSIS_OUTPUT_DIR }}/compliance_report.txt" \
          --rules "${RULES_PATH}" \
          -vv

    - name: Check for Vulnerabilities
      id: check-vulnerabilities
      run: |
        REPORT_PATH="analysis-results/compliance_report.txt"
    
        if [ ! -f "$REPORT_PATH" ]; then
          echo "::error::Compliance report not found"
          exit 1
        fi
    
        # Extract each violation block
        VIOLATION_BLOCKS=$(awk '/^- Rule ID:/ {found=1; print; next} found && NF==0 {found=0; print "---"} found && NF > 0 {print}' "$REPORT_PATH")
    
        # Count violations (based on "- Rule ID:" lines)
        VIOLATIONS_COUNT=$(echo "$VIOLATION_BLOCKS" | grep -c '^- Rule ID:')
    
        if [ "$VIOLATIONS_COUNT" -gt 0 ]; then
          echo "has_vulnerabilities=true" >> $GITHUB_ENV
          echo "::warning::Security vulnerabilities were found in the analysis"
          echo "Found $VIOLATIONS_COUNT violations in the analysis"
    
          echo "Violation Details:"
          echo "$VIOLATION_BLOCKS" | awk '
            /^- Rule ID:/ { rule=$0; next }
            /^  Location:/ {
              split($2, pathline, ":");
              file=pathline[1]; line=pathline[2];
              sub(/^- Rule ID: */, "", rule);
              printf "- Rule: %s, File: %s, Line: %s\n", rule, file, line
            }
          '
        else
          echo "has_vulnerabilities=false" >> $GITHUB_ENV
          echo "No security vulnerabilities found"
        fi



    - name: Upload Analysis Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cbom-analysis-results
        path: |
          ${{ env.ANALYSIS_OUTPUT_DIR }}/cbom.json
          ${{ env.ANALYSIS_OUTPUT_DIR }}/compliance_report.txt
        retention-days: 7

    - name: Create Analysis Summary
      if: always()
      run: |
        cd ${{ github.workspace }}
        REPORT_PATH="analysis-results/compliance_report.txt"
    
        echo "## CBOM Analysis Results" >> $GITHUB_STEP_SUMMARY
        echo "Analysis completed at: $(date)" >> $GITHUB_STEP_SUMMARY
        echo "### Repository Analyzed" >> $GITHUB_STEP_SUMMARY
        echo "Repository: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
        echo "Branch: ${GITHUB_REF#refs/heads/}" >> $GITHUB_STEP_SUMMARY
        echo "Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
    
        if [ ! -f "$REPORT_PATH" ]; then
          echo "### Compliance report not found." >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
    
        echo "### Security Violations Found" >> $GITHUB_STEP_SUMMARY
    
        # Extract violation blocks
        awk '
          /^- Rule ID:/ {in_rule=1; rule=$0; next}
          in_rule && /^  Location:/ {
            loc=$0;
            match(loc, /([^:]+):([0-9]+)/, arr);
            file=arr[1];
            line=arr[2];
            gsub(/^- Rule ID:[[:space:]]*/, "", rule);
            gsub(/  Location:[[:space:]]*/, "", loc);
            printf("#### Violation in `%s` at line %s\n", file, line) >> "summary.md";
            printf("- **Rule**: %s\n", rule) >> "summary.md";
            printf("- **File**: %s\n", file) >> "summary.md";
            printf("- **Line**: %s\n", line) >> "summary.md";
            
            if (system("[ -f \"" file "\" ]") == 0) {
              start = (line - 3 > 0) ? line - 3 : 1;
              end = line + 3;
              printf("**Affected Code:**\n\`\`\`c\n") >> "summary.md";
              cmd = sprintf("awk \'NR >= %d && NR <= %d { if (NR == %d) { printf(\"→ %%d: %%s\\n\", NR, $0) } else { printf(\"  %%d: %%s\\n\", NR, $0) }}\' %s", start, end, line, file);
              system(cmd " >> summary.md");
              printf("\`\`\`\n\n") >> "summary.md";
            } else {
              printf("File not found in workspace.\n\n") >> "summary.md";
            }
            in_rule=0;
          }
        ' "$REPORT_PATH"
    
        if [ -f summary.md ]; then
          cat summary.md >> $GITHUB_STEP_SUMMARY
          rm summary.md
        else
          echo "No violations found." >> $GITHUB_STEP_SUMMARY
        fi
    
        echo "---" >> $GITHUB_STEP_SUMMARY
        echo "### Full Reports" >> $GITHUB_STEP_SUMMARY
        echo "Detailed reports are available in the workflow artifacts:" >> $GITHUB_STEP_SUMMARY
        echo "- CBOM Report (cbom.json)" >> $GITHUB_STEP_SUMMARY
        echo "- Compliance Report (compliance_report.txt)" >> $GITHUB_STEP_SUMMARY


    - name: Fail if Vulnerabilities Found
      if: env.has_vulnerabilities == 'true'
      run: |
        echo "Security vulnerabilities were found in the analysis"
        exit 1
